name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  BUILD_TYPE: Release
jobs:
  build-ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install -y libgl-dev
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        CXX: g++-10
        CC: gcc-10
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      env:
        CXX: g++-10
        CC: gcc-10
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
  build-ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install -y libgl-dev
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        CXX: clang++
        CC: clang
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      env:
        CXX: clang++
        CC: clang
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: brew install libgl-dev
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        CXX: clang++
        CC: clang
  build-windows-msvc:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
